version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directories:
    - "/"
    - "/review"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
